security:
    encoders:
        RestBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: RestBundle:User
                property: email

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
