app_Rule:
    type: rest
    prefix: /v1
    resource: RestBundle\Controller\RulesController
    name_prefix:  api_1_ # naming collision
app_User:
    type: rest
    prefix: /v1
    resource: RestBundle\Controller\UsersController
    name_prefix:  api_1_
app_Transcription:
    type: rest
    prefix: /v1
    resource: RestBundle\Controller\TranscriptionsController
    name_prefix: api_1_
app_Language:
    type: rest
    prefix: /v1
    resource: RestBundle\Controller\LanguagesController
    name_prefix: api_1_