parameters:
  api.rule.class: RestBundle\Entity\Rule
  api.rule.handler.class: RestBundle\Handler\RuleHandler
  api.user.class: RestBundle\Entity\User
  api.user.handler.class: RestBundle\Handler\UserHandler
  api.transcription.factory.class: RestBundle\Transcription\TranscriptorFactory
  api.transcription.transcriptor.simple.class: RestBundle\Transcription\SimpleTranscriptor
  api.transcription.transcriptor.tree.class: RestBundle\Transcription\TreeTranscriptor

services:
  api.rule.handler:
    class: "%api.rule.handler.class%"
    arguments: [@doctrine.orm.entity_manager, "%api.rule.class%"]
  api.user.handler:
      class: "%api.user.handler.class%"
      arguments: [@doctrine.orm.entity_manager, "%api.user.class%"]
  api.transcription.factory:
    class: "%api.transcription.factory.class%"
    arguments: [@service_container]
  api.transcription.transcriptor.simple:
    class: "%api.transcription.transcriptor.simple.class%"
    arguments: [@api.rule.handler]
    load: lazy
  api.transcription.transcriptor.tree:
    class: "%api.transcription.transcriptor.tree.class%"
    arguments: [@api.rule.handler]
    load: lazy